workspace:
  base: /go
  path: src/git-jira

clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  core:
    image: golang:1.11
    environment:
      - GOPATH=/go
      - GO111MODULE=on
      - CGO_ENABLED=0
    commands:
      - go version
      - go mod download
      - go test -v
      - go build
      - ls -lA
      - rm git-jira
    when:
      event: [push, pull_request]
  release:
    image: golang:1.11
    secrets: [github_token]
    environment:
      - GOPATH=/go
      - GO111MODULE=on
      - CGO_ENABLED=0
    commands:
      - curl -sL https://git.io/goreleaser | bash -s release
    when:
      event: [tag]