before:
  hooks:
    - go mod download
builds:
  -
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - 386
    - amd64
    - arm
    - arm64
    goarm:
    - 6
    - 7
    ldflags:
    - -s -w -X main.Version={{.Tag}} -X main.Commit={{.Commit}}
archive:
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
  replacements:
    darwin: macos
    386: i386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  name: git-jira
  github:
    owner: tevjef
    name: homebrew-tap
  skip_upload: false
  commit_author:
    name: tevjef
    email: tev.jeffrey@gmail.com
  folder: Formula
  homepage: "https://github.com/tevjef/git-jira"
  dependencies:
  - git
